name: shoppe
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"


flutter:


  uses-material-design: true



  assets:
    - assets/images/
    - assets/images/auth/
    - assets/images/home/
    - assets/icons/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Italic-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/Raleway/static/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway/static/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway/static/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/static/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/static/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/static/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/static/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/static/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/static/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/static/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
    
